# Generated by Django 4.2.7 on 2024-01-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=20)),
                ("report_id", models.CharField(max_length=20)),
                ("file", models.FileField(upload_to="reports/")),
            ],
        ),
    ]
